services:
  - type: web
    name: ecommerce-laravale
    env: php
    plan: free
    buildCommand: |
      composer install
      npm install
      npm run prod
      php artisan migrate --force
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_KEY
        value: base64:M14OZ1NPyOdCpuIjcCenAUA3/DXCMdVWLlTEns9Mkws=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://ecommerce-laravale.onrender.com

    disk:
      name: storage
      mountPath: /var/www/storage
      sizeGb: 1
